# Site settings
title: Cigars eXPerience
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "The experience of making my own cigars from my own tobacco plants"
baseurl: "/cigarsxp"
url: "http://mihaigiurgeanu.github.io"
twitter_username: mgiurg
github_username:  mihaigiurgeanu
facebook_username:  mihaigiurgeanu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
